spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

cards:
  message: "Welcome to BrandonBank Cards related prod APIs "
  contactDetails:
    name: "Brandon Browns Sr - Product Owner"
    email: "brandon@brownsbank.com"
  onCallSupport:
    - (453) 392-4829
    - (236) 203-0384